name: 'CDN To Qiniu'

on: [push, delete]

jobs:
  run:
    name: 'cdn_to_qiniu'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Setup qshell'
      uses: foxundermoon/setup-qshell@v1
      with:
        qshell-version: '2.4.0'
    - name: 'Set Qiniu Key'
      run: qshell account ${{ QINIU_ACCESS_KEY }} ${{ QINIU_SECRET_KEY }} wsmud
    - name: 'CDN To Qiniu'
      run: qshell qupload2 --src-dir=${{ github.action_path }} --bucket=wsmud --rescan-local --overwrite --skip-path-prefixes "plugins/" --skip-suffixes ".DS_Store,.md" --skip-fixed-strings ".git,.vscode" --check-exists=true --check-hash=true